package dev.tbobm.mymymeal.app.food.domain.entity

import kotlinx.serialization.Serializable

@Serializable
data class RemoteNutritionFacts(
    val proteins: Double?,
    val carbohydrates: Double?,
    val fats: Double?,
    val energy: Double?,
    val saturatedFats: Double?,
    val transFats: Double?,
    val monounsaturatedFats: Double?,
    val polyunsaturatedFats: Double?,
    val omega3: Double?,
    val omega6: Double?,
    val sugars: Double?,
    val addedSugars: Double?,
    val salt: Double?,
    val dietaryFiber: Double?,
    val solubleFiber: Double?,
    val insolubleFiber: Double?,
    val cholesterol: Double?,
    val caffeine: Double?,
    val vitaminA: Double?,
    val vitaminB1: Double?,
    val vitaminB2: Double?,
    val vitaminB3: Double?,
    val vitaminB5: Double?,
    val vitaminB6: Double?,
    val vitaminB7: Double?,
    val vitaminB9: Double?,
    val vitaminB12: Double?,
    val vitaminC: Double?,
    val vitaminD: Double?,
    val vitaminE: Double?,
    val vitaminK: Double?,
    val manganese: Double?,
    val magnesium: Double?,
    val potassium: Double?,
    val calcium: Double?,
    val copper: Double?,
    val zinc: Double?,
    val sodium: Double?,
    val iron: Double?,
    val phosphorus: Double?,
    val selenium: Double?,
    val iodine: Double?,
    val chromium: Double?,
)
